# Generated by Django 4.1.3 on 2022-11-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category_coder_alter_language_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coder',
            name='language',
        ),
        migrations.AlterField(
            model_name='language',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Coder',
        ),
    ]
